graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 413
         y 114
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 634
         y 275
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 822
         y 81
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 426
         y 437
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 641
         y 485
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 861
         y 329
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 862
         y 538
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 654
         y 648
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 420
         y 688
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 436
         y 859
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 654
         y 823
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 847
         y 714
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 11
      label ""
      weight 1.0
   ]
]