graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 286
         y 96
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 526
         y 139
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 705
         y 365
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 441
         y 480
      ]
   ]
   node [
      id 4
      label "F"
      graphics [
         x 305
         y 340
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
]