graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "T"
      graphics [
         x 378
         y 150
      ]
   ]
   node [
      id 1
      label "F"
      graphics [
         x 627
         y 156
      ]
   ]
   node [
      id 2
      label "T"
      graphics [
         x 948
         y 158
      ]
   ]
   node [
      id 3
      label "F"
      graphics [
         x 905
         y 409
      ]
   ]
   node [
      id 4
      label "T"
      graphics [
         x 608
         y 399
      ]
   ]
   node [
      id 6
      label "T"
      graphics [
         x 366
         y 402
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 4
      label ""
      weight 1.0
   ]
]